### ISSUE TITLE
How to use in-browser

### ISSUE THREAD

**Issue by brannondorsey** [serain/netmap.js#5]
First off, I just want to say bravo for this whole lib. This is something I've long been interested in doing and I'm fascinated by your approach, especially for using image error callback delay to predict open TCP ports.

Forgive my naivety, but how does one actually include this code in the browser? I see you are using ES7+ features like import and module syntax, and you have babel in your `package.json`, but I see nothing in the source that suggests you are actually transpiling your JavaScript to a more browser-friendly version. I also attempted to include the example snippets in the README in `<script type="module"></script>` tags but no dice. Would you mind giving me some pointers, or including in your documentation, the steps that must be taken to actually deploy this in an `index.html` file? Hope I'm not overlooking something big...

Also, really nice job with the other DNS rebinding framework :+1:.

**Comment by brannondorsey** [comment]
Any hints w/ this?

**Comment by serain** [comment]
Hey Brannon, apologies for the delay, been zooming about all weekend.

Putting together a plug and play demo is on my to-do list but I'll have to free up some time before that.

Essentially, you need a web packer and an es6 transpiler to get this working. I'm not at all into front-end dev (these are my only projects) but it seems `webpack` is the reference (it's what I use). I think `webpack` comes es6 ready now, so once you've followed the getting started tutorials, it should all be straightforward. If not you'll need to look at setting up `babel` with `webpack` for es6 transpilation.

I used this to get started with webpack https://webpack.js.org/guides/getting-started/

Let me know how you get on! Don't hesitate to drop me any questions.

**Comment by serain** [comment]
How are you getting on with this? Feel free to DM me on Twitter

**Comment by brannondorsey** [comment]
Thanks a bunch for your response. Sorry for the delay. I've been in NYC for HOPE and haven't yet had a chance to revisit this just yet. I intend to soon though and will ping you if I hit a snag. Otherwise I expect webpack to work, if it did for you :)

**Comment by brannondorsey** [comment]
Finally getting another chance to have a look at this. At first try I'm still not having luck building this. I don't have a lot of experience with Webpack. I have tried with [Parcel](https://parceljs.org/), and it appears I have a valid build, but `pingSweep()` doesn't make any requests...

Would you mind including a build in this repo or add your webpack build process as an npm build script?

**UPDATE**: I think I've got a build working with webpack, but I I think including your *canonical* build process in this repo would be really helpful. Do you have a `webpack.config.js` file? Adding that and an npm build script would be awesome.
